services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - rd-data:/data
    ports:
      - "6479:6479"
    restart: unless-stopped

  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  pg-data:
  rd-data: